apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust
    role: worker
spec:
  replicas: 1
  template:
    metadata:
      name: locust
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust-worker
          image: savvagench/locust:latest
          env:
            - name: LOCUST_MODE
              value: single
            - name: TARGET_HOST
              value: http://localhost:3000
            - name: LOCUSTFILE_PATH
              value: locust_scenarios/load_test.py
            - name: LOCUST_TEST
              value: JsonServerScenario
            - name: ADD_OPTIONS
              value: -c 10 -r 5 -t3m30s --no-web
            - name: MAX_LATENCY
              value: "11000"
#            - name: LOAD_TEST_TIMEOUT # test timeout in seconds for timeout_listener
#              value: "120"
#            - name: MAX_REQUESTS # set max number requests to be generated - the same as Taurus "iterations"
#              value: 10000
# Enable master FIXED_RPS listeners with variables
#            - name: TARGET_RPS
#              value: "15"
#            - name: SLAVE_COUNT
#              value: "4"
# Add additional command
            - name: ADD_COMMAND
              value: "ls -la && echo start sleeping for 10 sec. && sleep 10 && echo Stopping Container."
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
            - name: loc-master-p3
              containerPort: 5559
              protocol: TCP
            - name: loc-master-p4
              containerPort: 5560
              protocol: TCP
            - name: loc-master-p5
              containerPort: 5561
              protocol: TCP
            - name: loc-master-p6
              containerPort: 5562
              protocol: TCP
            - name: loc-master-p7
              containerPort: 5563
              protocol: TCP
          volumeMounts:
            - name: tests
              mountPath: /locust-tasks
              readOnly: true
            - name: locust-scenarios
              mountPath: /locust-tasks/locust_scenarios
              readOnly: true
            - name: taurus-configs
              mountPath: /locust-tasks/taurus_configs
              readOnly: true
            - name: hooks
              mountPath: /locust-tasks/hooks
              readOnly: true
      volumes:
        - name: tests
          configMap:
            name: tests
        - name: locust-scenarios
          configMap:
            name: locust-scenarios
        - name: hooks
          configMap:
            name: hooks
        - name: taurus-configs
          configMap:
            name: taurus-configs
---
# ---- Create LOCUST Services ----
kind: Service
apiVersion: v1
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust
    role: worker
spec:
  ports:
    - port: 8089
      targetPort: loc-worker-web
      protocol: TCP
      name: loc-worker-web
  selector:
    name: locust
    role: worker
  type: LoadBalancer