# ---- Create LOCUST slaves(workers) Deployment----
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust
    role: worker
spec:
  replicas: 2
  template:
    metadata:
      name: locust-worker
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust-worker
          image: savvagench/locust:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: http://localhost:3000
            - name: LOCUST_TEST
              value: JsonServerScenario
            - name: LOCUSTFILE_PATH
              value: locust_scenarios/load_test.py
            - name: ADD_OPTIONS
              value: --logfile=locust-slave.log
            - name: MAX_LATENCY
              value: "11000"
            - name: ADD_COMMAND
              value: "ls -la && echo start sleeping for 10 sec. && sleep 10 && echo Stopping Container."
          volumeMounts:
            - name: tests
              mountPath: /locust-tasks
              readOnly: true
            - name: locust-scenarios
              mountPath: /locust-tasks/locust_scenarios
              readOnly: true
            - name: taurus-configs
              mountPath: /locust-tasks/taurus_configs
              readOnly: true
            - name: hooks
              mountPath: /locust-tasks/hooks
              readOnly: true
      volumes:
        - name: tests
          configMap:
            name: tests
        - name: locust-scenarios
          configMap:
            name: locust-scenarios
        - name: hooks
          configMap:
            name: hooks
        - name: taurus-configs
          configMap:
            name: taurus-configs