apiVersion: v1
kind: Namespace
metadata:
  name: locust
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: locust
  name: locust
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: locust
  namespace: locust
roleRef:
  kind: Role
  name: locust
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: locust
  name: default
