version: "3.4"

x-common: &common
  image: savvagench/locust:latest
  volumes: &common-volumes
    volumes:
      - $PWD:/locust-tasks/load_test
      - $PWD/reports:/locust-tasks/reports
  environment: &common-env
    TARGET_HOST: http://localhost:3000
    LOCUSTFILE_PATH: scenarios/load_test.py
    LOCUST_TEST: JsonServerSecnario
    # env variables for locust tests
    MAX_LATENCY: 11000 # use this variable when LatencyListener is enabled
    # TARGET_RPS: 10   # use this variable when FixedRPS listeners are enabled.
    # SLAVES_COUNT: 2  # use this variable when FixedRPS listeners are enabled.


services:

  master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master
      # EXPECT_SLAVES: 2 # Add this variable when the number of slaves is limited
      ADD_OPTIONS: "--no-web -c 10 -r 2 -t2m10s --loglevel=INFO --print-stats --csv=reports/locust-report"
    <<: *common-volumes
    networks:
      - loadtest
    hostname: master
    container_name: master

  slave1:
    <<: *common
    links:
      - master
    environment:
      <<: *common-env
      LOCUST_MODE: worker
      LOCUST_MASTER: master
    <<: *common-volumes
    networks:
      - loadtest
    container_name: slave1

  slave2:
    <<: *common
    links:
      - master
    environment:
      <<: *common-env
      LOCUST_MODE: worker
      LOCUST_MASTER: master
    <<: *common-volumes
    networks:
      - loadtest
    container_name: slave2

networks:
  loadtest:
    driver: bridge