apiVersion: batch/v1
kind: Job
metadata:
  name: locust-taurus-job
  namespace: locust
  labels:
    name: locust-taurus-job
    role: standalone
spec:
  # completions: 2
  # parallelism: 2
  # backoffLimit: 4
  # activeDeadlineSeconds: 180 # After reaching Job timeout - job status will become type: Failed with reason: DeadlineExceeded
  # ttlSecondsAfterFinished: 20 # AVAILABLE IN KUBERNETES VERSION 1.12
  template:
    metadata:
      name: locust
      labels:
        name: locust-taurus-job
        role: standalone
    spec:
      restartPolicy: Never
      containers:
        - name: locust-taurus-job
          image: savvagench/taurus:latest
          env:
            - name: TARGET_HOST
              value: http://localhost:3000
            - name: TAURUS_CONFIG
              value: taurus_configs/load_test.yml
            - name: ADD_OPTIONS
              value: -report # -o settings.artifacts-dir=test_artifacts
            - name: MAX_LATENCY
              value: "9000"
#            - name: LOAD_TEST_TIMEOUT # test timeout in seconds for timeout_listener
#              value: "120"
#            - name: MAX_REQUESTS # set max number requests to be generated - the same as Taurus "iterations"
#              value: 10000
# Enable master FIXED_RPS listeners with variables
#            - name: TARGET_RPS
#              value: "15"
#            - name: SLAVE_COUNT
#              value: "4"
            - name: ADD_COMMAND
              value: "ls -la && echo start sleeping for 10 sec. && sleep 10 && echo Stopping Container."
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: scenarios
              mountPath: /bzt-configs/locust_scenarios
              readOnly: true
            - name: hooks
              mountPath: /bzt-configs/hooks
              readOnly: true
            - name: bzt-configs
              mountPath: /bzt-configs/taurus_configs
              readOnly: true
      volumes:
        - name: examples
          configMap:
            name: examples
        - name: scenarios
          configMap:
            name: scenarios
        - name: hooks
          configMap:
            name: hooks
        - name: bzt-configs
          configMap:
            name: bzt-configs